"""DDL 분석 결과 → SQL 파일 생성."""
from __future__ import annotations
from pathlib import Path
from ddl_agent.models import ExtractedDDL


def to_sql(ddl: ExtractedDDL) -> str:
    lines: list[str] = []
    lines.append(f"-- DDL generated by ddl-agent (dialect: {ddl.dialect})")
    lines.append("")

    for table in ddl.tables:
        tname = f"{table.schema_name}.{table.name}" if table.schema_name else table.name
        lines.append(f"CREATE TABLE {tname} (")

        col_defs: list[str] = []
        for col in table.columns:
            parts = [f"  {col.name}", col.type]
            if col.auto_increment:
                if ddl.dialect in ("postgresql", "postgres"):
                    parts[1] = "SERIAL" if col.type.upper() in ("INT", "INTEGER") else "BIGSERIAL"
                else:
                    parts.append("AUTO_INCREMENT")
            if not col.nullable:
                parts.append("NOT NULL")
            if col.unique:
                parts.append("UNIQUE")
            if col.default is not None:
                parts.append(f"DEFAULT {col.default}")
            if col.comment:
                parts.append(f"COMMENT '{col.comment}'")
            col_defs.append(" ".join(parts))

        for cst in table.constraints:
            if cst.type == "PRIMARY KEY":
                col_defs.append(f"  CONSTRAINT {cst.name} PRIMARY KEY ({', '.join(cst.columns)})")
            elif cst.type == "FOREIGN KEY" and cst.ref_table:
                col_defs.append(
                    f"  CONSTRAINT {cst.name} FOREIGN KEY ({', '.join(cst.columns)}) "
                    f"REFERENCES {cst.ref_table} ({', '.join(cst.ref_columns)})"
                )
            elif cst.type == "UNIQUE":
                col_defs.append(f"  CONSTRAINT {cst.name} UNIQUE ({', '.join(cst.columns)})")

        lines.append(",\n".join(col_defs))
        lines.append(");")

        if table.comment and ddl.dialect in ("postgresql", "postgres"):
            lines.append(f"COMMENT ON TABLE {tname} IS '{table.comment}';")

        lines.append("")

    return "\n".join(lines)


def write_ddl(ddl: ExtractedDDL, out_path: Path) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(to_sql(ddl), encoding="utf-8")
    return out_path
